version: '3'
services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - .:/usr/app
    restart: on-failure
    env_file: .env
  mysql:
    image: mysql:8.0.31
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authenticated_api
    ports:
      - 3306:3306
volumes:
  mysql-data:
